AccesoPaso1/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AccesoPaso1.Models;

namespace AccesoPaso1.Controllers
{
    public class CarroController : Controller
    {
        // GET: Carro
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Agregar(int id)
        {
            ProdCarro carro = new ProdCarro();
            if (Session["cart"]==null)
            {
                List<Item> cart = new List<Item>();
                producto P = carro.find(id);
                string nam = P.nombre;
                cart.Add(new Item { Product = carro.find(id), Cantidad = 1 });
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Cantidad++;
                }
                else
                {
                    producto P = carro.find(id);
                    string nam = P.nombre;
                    cart.Add(new Item { Product = carro.find(id), Cantidad = 1 });
                }
                Session["cart"] = cart;
            }
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i=0; i<cart.Count; i++)
            {
                if (cart[i].Product.Id_producto.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

        public ActionResult Quitar(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            int index = isExist(id);
            Session["cart"] = cart;
            return RedirectToAction("Index");
        }
    }
}

AccesoPaso1/Controllers/CatalogoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AccesoPaso1.Models;

namespace AccesoPaso1.Controllers
{
    [Authorize]
    public class CatalogoController : Controller
    {
        private contextTienda db = new contextTienda();
        // GET: Catalogo
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BuscarProd(String nomBuscar)
        {
            ViewBag.SearchKey = nomBuscar;
            using (db)
            {
                var query = from st in db.producto
                            where st.nombre.Contains(nomBuscar)
                            select st;

                var listProd = query.ToList();
                ViewBag.Listado = listProd;
            }
            return View();
        }

       public ActionResult prodCategoria(int idCat)
        {
            List<producto> mercancia = null;
            var query = from p in db.producto
                        where p.id_categoria == idCat
                        select p;

            if (idCat == 1)
            {
                List<producto> toallas = query.ToList();
                mercancia = toallas;
                ViewBag.Catego = "Toallas";
                
            }
            if (idCat == 2)
            {
                List<producto> piel = query.ToList();
                mercancia = piel;
                ViewBag.Catego = "Piel";
            }
            ViewBag.productos = mercancia;
            return View();
        }
    }
}

AccesoPaso1/Views/Catalogo/BuscarProd.cshtml
@using AccesoPaso1.Models
@{
    ViewBag.Title = "BuscarProd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Lista de productos con nombre @ViewBag.SearchKey</h3>
<table cellpadding="2" cellspacing="2" border="1">
    <tr>
        <th>Nombre</th>
        <th>Foto</th>
        <th>Precio</th>
        <th>Comprar</th>
    </tr>
    @foreach (producto producto in ViewBag.Listado)
    {
        <tr>
            <th>@producto.nombre</th>
            <th><img src="~/Content/img/productos/@producto.imagen"</th>
            <th>@producto.precio</th>
            <th align="center">
                <a href="@Url.Action("Comprar","Carro",new { id= producto.Id_producto})"></a>
            </th>
        </tr>
    }
</table>

AccesoPaso1/Views/Catalogo/prodCategoria.cshtml
@using AccesoPaso1.Models
@{
    ViewBag.Title = "prodCategoria";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Catego</h2>

<div class="container">
    <div class="col-xs-12 col-md-9">
        <div class="row">
            @foreach(producto item in ViewBag.productos)
            {
                <div class="col-xs-12 col-md-3">
                    <div class="thumbnail">
                        <img class="img-responsive" src="~/Content/img/@item.imagen" />
                        <div class=" caption text-center" >
                            <p>
                                <b>Nombre: </b><span>@item.nombre</span>
                            </p>
                            <p>
                                <b>Precio: </b><span>@item.precio</span>
                            </p>
                            <p class="text-center">
                                @Html.ActionLink("Añadir al carrito", "Agregar", "Carro", new { id = item.Id_producto }, new { @class = "btn btn-info" })
                            </p>
                        </div>
                    </div>
                </div>

            }
        </div>
    </div>
</div>